/*
 * Copyright (C) 2021-2026, Dylan Liu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file new_identity_algorithm.h
 * @brief Template for implementing a custom identity signing algorithm as a shared library plugin.
 * @details This file provides a skeleton implementation of an identity signing algorithm
 *          that can be loaded at runtime by the ChordAuditMatrix hot-load system.
 *
 *          The template inherits from `IdentitySigningAlgorithm` and implements all
 *          required virtual methods with empty stubs. Users should fill in the actual
 *          cryptographic logic for their custom identity algorithm.
 *
 *          Identity signing algorithms support two core operations:
 *          - **Sign**: Sign a message with a user's private key
 *          - **AggregateVerify**: Verify an aggregate signature from multiple signers
 *
 *          Key management follows a two-tier hierarchy:
 *          1. **Master key pair** — generated by `generateMasterKey()`
 *          2. **User key pair** — derived from master key + user ID via `deriveUserKey()`
 *
 *          The C-linkage factory functions `create_identity_algorithm()` and
 *          `destroy_identity_algorithm()` are automatically exported for dynamic
 *          loading via `dlopen`/`dlsym`.
 *
 * @author Dylan Liu
 * @version 1.0.0
 * @date 2026-07-12
 * @copyright Copyright (C) 2021 - 2026, Dylan Liu
 */

#ifndef NEW_IDENTITY_ALGORITHM_H
#define NEW_IDENTITY_ALGORITHM_H

#include "ChordAuditMatrixLib/interfaces/identity/identity_signing_algorithm.h"
#include "ChordAuditMatrixLib/interfaces/identity/identity_algorithm_params.h"
#include "ChordAuditMatrixLib/interfaces/identity/identity_request.h"
#include "ChordAuditMatrixLib/interfaces/audit/messages/audit_data_map.h"

#include <memory>
#include <stdexcept>

namespace CAMatrix::Identity::Strategies {

using namespace CAMatrix::Identity::Core;
using CryptoArray = CAMatrix::Crypto::CryptoArray;
using AuditDataMap = CAMatrix::Audit::Messages::AuditDataMap;

/**
 * @class NewIdentityAlgorithm
 * @brief Skeleton implementation of a custom identity signing algorithm.
 * @details Users should inherit from `IdentitySigningAlgorithm` and implement
 *          all pure virtual methods:
 *
 *          **Key Management** (two-tier hierarchy):
 *          - `generateMasterKey()` — Generate the master key pair (mpk, msk)
 *          - `deriveUserKey()`    — Derive a user's key pair from master key + user ID
 *
 *          **Core Operations**:
 *          - `sign()`             — Sign a message with the user's private key
 *          - `aggregateVerify()`  — Verify an aggregate signature from multiple signers
 *
 *          **Parameter Factory** (for deserialization):
 *          - `createPublicParams()`       — Create concrete AlgoPublicParams
 *          - `createPrivateParams()`      — Create concrete AlgoPrivateParams
 *          - `createUserPublicParams()`   — Create concrete AlgoUserPublicParams
 *          - `createUserPrivateParams()`  — Create concrete AlgoUserPrivateParams
 *
 *          **Request Creation**:
 *          - `createRequest()`    — Convert AuditDataMap → typed SignRequest or AggregateVerifyRequest
 */
class NewIdentityAlgorithm : public IdentitySigningAlgorithm {
public:
    NewIdentityAlgorithm();
    ~NewIdentityAlgorithm() override;

    // ── PluggableAlgorithm interface ──

    std::string algorithmType() const override { return "NewIdentity"; }
    std::string version() const override { return "1.0.0"; }

    // ── Key generation ──

    std::pair<std::shared_ptr<AlgoPublicParams>,
              std::shared_ptr<AlgoPrivateParams>>
    generateMasterKey() override;

    std::pair<std::shared_ptr<AlgoUserPublicParams>,
              std::shared_ptr<AlgoUserPrivateParams>>
    deriveUserKey(
        const AlgoPublicParams& masterPub,
        const AlgoPrivateParams& masterPriv,
        const std::string& userId) override;

    // ── Request creation (AuditDataMap → typed) ──

    IdentityRequestVariantPtr createRequest(
        IdentityOperation op,
        const AuditDataMap& input) override;

    // ── Core operations ──

    CryptoArray sign(const SignRequest& req) override;
    bool aggregateVerify(const AggregateVerifyRequest& req) override;

    // ── Factory methods for deserialization ──

    std::shared_ptr<AlgoPublicParams> createPublicParams() const override;
    std::shared_ptr<AlgoPrivateParams> createPrivateParams() const override;
    std::shared_ptr<AlgoUserPublicParams> createUserPublicParams() const override;
    std::shared_ptr<AlgoUserPrivateParams> createUserPrivateParams() const override;
};

} // namespace CAMatrix::Identity::Strategies

// ── C-linkage factory functions for dynamic loading ──
// These are resolved by AlgorithmHotLoadDecorator via dlsym/GetProcAddress.

extern "C" CAMatrix::Identity::Core::IdentitySigningAlgorithm* create_identity_algorithm() noexcept
{
    return new CAMatrix::Identity::Strategies::NewIdentityAlgorithm();
}

extern "C" void destroy_identity_algorithm(CAMatrix::Identity::Core::IdentitySigningAlgorithm* p) noexcept
{
    delete p;
}

#endif // NEW_IDENTITY_ALGORITHM_H
