/*
 * Copyright (C) 2021-2026, Dylan Liu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file new_online_identity_algorithm.h
 * @brief Template for implementing an online identity signing algorithm as a shared library plugin.
 * @details This file provides a skeleton implementation of an online identity signing algorithm
 *          that can be loaded at runtime by the ChordAuditMatrix hot-load system.
 *
 *          The template inherits from `OnlineIdentitySigningAlgorithm` and implements all
 *          required virtual methods with empty stubs. Users should fill in the actual
 *          cryptographic logic for their custom identity algorithm.
 *
 *          Online identity algorithms require a coordinator to publish a shared session
 *          string before signing. Every signature and the later aggregation are bound
 *          to that session. The coordination mode `kind()` is finalized by the tier to
 *          `IdentityAlgorithmKind::Online` and is inherited as-is — it must NOT be
 *          reimplemented in this class.
 *
 *          Session contract (from the online tier):
 *          1. `makeSessionString()`          — session string construction;
 *          2. `validateSessionString()`      — session string validation;
 *          3. `aggregateSessionSignatures()` — in-session aggregation.
 *          Invariants: session strings are unique across sessions, and a single signer
 *          signs at most once per session.
 *
 *          Key management follows a two-tier hierarchy:
 *          1. **Master key pair** — generated by `generateMasterKey()`
 *          2. **User key pair** — derived from master key + user ID via `deriveUserKey()`
 *
 *          The C-linkage factory functions `create_identity_algorithm()` and
 *          `destroy_identity_algorithm()` are declared in CoreLib's
 *          `identity_signing_algorithm.h` and defined in the matching .cpp file,
 *          so they are automatically exported for dynamic loading via
 *          `dlopen`/`dlsym`.
 *
 * @author Dylan Liu
 * @version 1.0.0
 * @date 2026-08-25
 * @copyright Copyright (C) 2021 - 2026, Dylan Liu
 */

#ifndef NEW_ONLINE_IDENTITY_ALGORITHM_H
#define NEW_ONLINE_IDENTITY_ALGORITHM_H

#include "ChordAuditMatrixLib/interfaces/identity/online_identity_signing_algorithm.h"
#include "ChordAuditMatrixLib/interfaces/identity/identity_algorithm_params.h"
#include "ChordAuditMatrixLib/interfaces/identity/identity_request.h"
#include "ChordAuditMatrixLib/interfaces/audit/messages/audit_data_map.h"

#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

namespace CAMatrix::Identity::Strategies {

using namespace CAMatrix::Identity::Core;
using CryptoArray = CAMatrix::Crypto::CryptoArray;
using AuditDataMap = CAMatrix::Audit::Messages::AuditDataMap;

/**
 * @class NewOnlineIdentityAlgorithm
 * @brief Skeleton implementation of an online identity signing algorithm.
 * @details Users should inherit from `OnlineIdentitySigningAlgorithm` and implement
 *          all pure virtual methods:
 *
 *          **Key Management** (two-tier hierarchy):
 *          - `generateMasterKey()` — Generate the master key pair (mpk, msk)
 *          - `deriveUserKey()`    — Derive a user's key pair from master key + user ID
 *
 *          **Session Contract** (coordinator-published session string):
 *          - `makeSessionString()`          — Construct the session string
 *                                             (sessionString = sessionId ‖ context)
 *          - `validateSessionString()`      — Validate a session string's format/domain
 *          - `aggregateSessionSignatures()` — Aggregate in-session signatures
 *
 *          **Core Operations**:
 *          - `sign()`             — Sign a message with the user's private key
 *          - `aggregateVerify()`  — Verify an aggregate signature from multiple signers
 *
 *          **Parameter Factory** (for deserialization):
 *          - `createPublicParams()`       — Create concrete AlgoPublicParams
 *          - `createPrivateParams()`      — Create concrete AlgoPrivateParams
 *          - `createUserPublicParams()`   — Create concrete AlgoUserPublicParams
 *          - `createUserPrivateParams()`  — Create concrete AlgoUserPrivateParams
 *
 *          **Request Creation**:
 *          - `createRequest()`    — Convert AuditDataMap → typed SignRequest or AggregateVerifyRequest
 *
 *          `kind()` is finalized by `OnlineIdentitySigningAlgorithm` and must NOT
 *          be overridden.
 */
class NewOnlineIdentityAlgorithm : public OnlineIdentitySigningAlgorithm {
public:
    NewOnlineIdentityAlgorithm();
    ~NewOnlineIdentityAlgorithm() override;

    // ── PluggableAlgorithm interface ──

    std::string algorithmType() const override { return "NewOnlineIdentity"; }
    std::string version() const override { return "1.0.0"; }

    // ── Key generation ──

    std::pair<std::shared_ptr<AlgoPublicParams>,
              std::shared_ptr<AlgoPrivateParams>>
    generateMasterKey() override;

    std::pair<std::shared_ptr<AlgoUserPublicParams>,
              std::shared_ptr<AlgoUserPrivateParams>>
    deriveUserKey(
        const AlgoPublicParams& masterPub,
        const AlgoPrivateParams& masterPriv,
        const std::string& userId) override;

    // ── Request creation (AuditDataMap → typed) ──

    IdentityRequestVariantPtr createRequest(
        IdentityOperation op,
        const AuditDataMap& input) override;

    // ── Core operations ──

    CryptoArray sign(const SignRequest& req) override;
    CryptoArray aggregate(const AggregateRequest& req) override;
    bool aggregateVerify(const AggregateVerifyRequest& req) override;
    // ── Session contract (online tier) ──

    std::string makeSessionString(
        const std::string& sessionId,
        const std::string& context) const override;

    bool validateSessionString(const std::string& sessionString) const override;

    CryptoArray aggregateSessionSignatures(
        const std::vector<CryptoArray>& signatures,
        const std::string& sessionString) override;

    // ── Factory methods for deserialization ──

    std::shared_ptr<AlgoPublicParams> createPublicParams() const override;
    std::shared_ptr<AlgoPrivateParams> createPrivateParams() const override;
    std::shared_ptr<AlgoUserPublicParams> createUserPublicParams() const override;
    std::shared_ptr<AlgoUserPrivateParams> createUserPrivateParams() const override;
};

} // namespace CAMatrix::Identity::Strategies

#endif // NEW_ONLINE_IDENTITY_ALGORITHM_H
